### ISSUE TITLE
[BUG] Very verbose GPU output

### ISSUE THREAD

**Issue by CIAvash** [HorlogeSkynet/archey4#111]
**Describe the bug**
The output of GPU entry for AMD 6900 XT is very verbose. It shows:
```
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c0)
```

**Expected behavior**
More concise GPU output, for example, neofetch shows this:
```
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
```

**Environment**

 - Version used (4.Y.Z) : 4.13.4
 - Method of installation (distribution package, PyPI, Homebrew, sources) : AUR
 - Hardware type (laptop, server, Raspberry, hyper-visor) : Desktop
 - Python version (3.Y.Z) : 3.10.3
 - Operating system and version : Arch Linux (Linux 5.16.16-arch1-1)
 - Graphical environment name and version : Sway window manager
 - Connectivity (off-line, LAN only, Internet access) : Internet

**Comment by HorlogeSkynet** [comment]
Hi @CIAvash

It's true that Archey does not assume anything about GPU data format, and simply shows it all ([ref](https://github.com/HorlogeSkynet/archey4/blob/f7daf623f65c06bde0299ccc2b48d663fcaa88ba/archey/entries/gpu.py#L45)).
On the other hand, Neofetch performs extended parsing, and specifically for your GPU ([ref](https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L2535)).

I don't really know what we should/could do about it here, because looking at Neofetch code, this really looks like vendor-related parsing (which I'd rather avoid, because of the maintaining burden).

I'm opened to any idea though, including changing or preferring another data source on GNU/Linux platforms.

Cheers 👋

**Comment by CIAvash** [comment]
`hwinfo` shows a shorter output:
```console
hwinfo --short | rg -A 1 'graphics card:' | sd '\s+' ' '
```
```
graphics card: ATI Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
```

`lshw`:
```console
lshw -C display 2>/dev/null | rg product
```
```
product: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
```

That said, how about adding a field to run custom commands? For example a `custom_command` field. Or even better allow adding custom entries in which users can run custom commands. What do you think?

**Comment by HorlogeSkynet** [comment]
Hi @CIAvash, please tell me if #113 implementation draft fits your needs :pray:

**Comment by CIAvash** [comment]
Hi @HorlogeSkynet, yes, it works perfectly. Thanks!
