### ISSUE TITLE
[BUG] [DISK] [BUSYBOX] Entry is not detected

### ISSUE THREAD

**Issue by HorlogeSkynet** [HorlogeSkynet/archey4#62]
**Describe the bug**
On Alpine Linux, for instance, the `Disk` entry is left undetected.
See <https://github.com/HorlogeSkynet/archey4/commit/d676b0b2d58c4a4f0e6beefcfbd5456f0165a6ec#diff-e6076e0f8c9ab0586c8909ec8d6832beR67>.

**Additional context**
When fixing this (let's say with a simpler `df -P -B M` call and a proper columns parsing), we've to think about an _optimized_ approach, as while checking for BTRFS mount-points, the second `df` call would also fail...
Maybe this fix could be thought over while reworking `Disk` for #55.

**Comment by ingrinder** [comment]
If we stick with `df`, we should probably go with `df -k -P`, since that's about as much as we can do following the original UNIX specification (see [here](https://en.wikipedia.org/wiki/Df_%28Unix%29#Usage)) and convert the 1024-byte blocks into a human readable size. That should give us the most compatibility with anything *NIX.

**Comment by HorlogeSkynet** [comment]
I think we will/should ; It's fast, relevant and pretty-well supported.
So agreed :100:
Although, as we will lose `-l`, it's definitely relevant to work this out during #55, with the upcoming ability to specify mount-points.

> Note to myself : Maybe it's time to rework the way we invoke `ps` in `Processes` at the same time.
> Current best candidate : `ps -eo comm`. Header line will have to be ignored.

**Comment by HorlogeSkynet** [comment]
This will be indirectly fixed by #67 ; closing here.
